import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "12 Rules for Life: An Antidote to Chaos",
    img: "https://images-na.ssl-images-amazon.com/images/I/41kspFBwVxL._SX331_BO1,204,203,200_.jpg",
    originalPrice: 2000,
    discountedPrice: 1900,
    discount: 30,
    author: "Jordan B. Peterson",
    rating: "4.5",
    cover: "hardcover",
    category: "bestseller",
  },
  {
    _id: uuid(),
    title: "Beyond Order: 12 More Rules for Life",
    img: "https://images-na.ssl-images-amazon.com/images/I/41Bhl964Z3L._SX325_BO1,204,203,200_.jpg",
    originalPrice: 600,
    discountedPrice: 250,
    discount: 20,
    author: "Jordan B. Peterson",
    rating: "4.5",
    cover: "hardcover",
    category: "fiction",
  },
  {
    _id: uuid(),
    title:
      "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    img: "https://images-na.ssl-images-amazon.com/images/I/51-nXsSRfZL._SX328_BO1,204,203,200_.jpg",
    originalPrice: 600,
    discountedPrice: 350,
    discount: 10,
    author: "James Clear",
    rating: "4.6",
    cover: "softcover",
    category: "fiction",
  },
  {
    _id: uuid(),
    title: "The 48 Laws Of Power by Robert Greene",
    img: "https://images-na.ssl-images-amazon.com/images/I/41VCBqRMNML._SX351_BO1,204,203,200_.jpg",
    originalPrice: 1200,
    discountedPrice: 420,
    discount: 60,
    author: "Robert Greene",
    rating: "4.8",
    cover: "softcover",
    category: "bestseller",
  },
  {
    _id: uuid(),
    title: "The Laws of Human Nature ",
    img: "https://images-na.ssl-images-amazon.com/images/I/41PUWqRghSL._SX323_BO1,204,203,200_.jpg",
    originalPrice: 699,
    discountedPrice: 489,
    discount: 30,
    author: "Robert Greene",
    rating: "4.5",
    cover: "hardcover",
    category: "bestseller",
  },
  {
    _id: uuid(),
    title: "Mastery book by Robert Greene",
    img: "https://images-na.ssl-images-amazon.com/images/I/41T1+apx5SL._SX325_BO1,204,203,200_.jpg",
    originalPrice: 699,
    discountedPrice: 467,
    discount: 30,
    author: "Robert Greene",
    rating: "4.6",
    cover: "softcover",
    category: "fiction",
  },
  {
    _id: uuid(),
    title:
      "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    img: "https://images-na.ssl-images-amazon.com/images/I/51-nXsSRfZL._SX328_BO1,204,203,200_.jpg",
    originalPrice: 600,
    discountedPrice: 350,
    discount: 10,
    author: "James Clear",
    rating: "4.6",
    cover: "softcover",
    category: "fiction",
  },
  {
    _id: uuid(),
    title: "The 48 Laws Of Power by Robert Greene",
    img: "https://images-na.ssl-images-amazon.com/images/I/41VCBqRMNML._SX351_BO1,204,203,200_.jpg",
    originalPrice: 1200,
    discountedPrice: 420,
    discount: 60,
    author: "Robert Greene",
    rating: "4.8",
    cover: "softcover",
    category: "bestseller",
  },
  {
    _id: uuid(),
    title: "The Laws of Human Nature by Robert Greene",
    img: "https://images-na.ssl-images-amazon.com/images/I/41PUWqRghSL._SX323_BO1,204,203,200_.jpg",
    originalPrice: 699,
    discountedPrice: 489,
    discount: 30,
    author: "Robert Greene",
    rating: "4.5",
    cover: "hardcover",
    category: "bestseller",
  },
  {
    _id: uuid(),
    title: "Mastery book by Robert Greene",
    img: "https://images-na.ssl-images-amazon.com/images/I/41T1+apx5SL._SX325_BO1,204,203,200_.jpg",
    originalPrice: 699,
    discountedPrice: 467,
    discount: 30,
    author: "Robert Greene",
    rating: "4.6",
    cover: "softcover",
    category: "fiction",
  },
];
